---
title: "Mixture Models"
author: "MLDL"
date: "4/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mixture Model Fun

Stealing from Julie Silge's blog [here](https://juliasilge.com/blog/kmeans-employment/), well first start where she did, but then turn to using a mixture model to define clusters to see the differences and to try things in R.

```{r}
# Bring in all that she did prior to modeling. 
library(tidyverse)

employed <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-23/employed.csv")

employed_tidy <- employed %>%
  filter(!is.na(employ_n)) %>%
  group_by(occupation = paste(industry, minor_occupation), race_gender) %>%
  summarise(n = mean(employ_n)) %>%
  ungroup()

employment_demo <- employed_tidy %>%
  filter(race_gender %in% c("Women", "Black or African American", "Asian")) %>%
  pivot_wider(names_from = race_gender, values_from = n, values_fill = 0) %>%
  janitor::clean_names() %>%
  left_join(employed_tidy %>%
    filter(race_gender == "TOTAL") %>%
    select(-race_gender) %>%
    rename(total = n)) %>%
  filter(total > 1e3) %>%
  mutate(across(c(asian, black_or_african_american, women), ~ . / (total)),
    total = log(total),
    across(where(is.numeric), ~ as.numeric(scale(.)))
  ) %>%
  mutate(occupation = snakecase::to_snake_case(occupation))

employment_demo
```

```{r}
employment_clust <- kmeans(select(employment_demo, -occupation), centers = 3)
summary(employment_clust)
```

```{r}
library(broom)
tidy(employment_clust)
```

```{r}
augment(employment_clust, employment_demo) %>%
  ggplot(aes(total, black_or_african_american, color = .cluster)) +
  geom_point()
```

Fantastic, there are three clusters (which is fairly nominal, as this was pre-elbow plot assessment). 

Using the `mclust` package, we'll take a stab at it. 

```{r}
library(mclust)
# see: https://mclust-org.github.io/mclust/articles/mclust.html
model <- Mclust(employment_demo %>% select(-occupation),
                3)
```

```{r}
summary(model, parameters = TRUE)
```

```{r}
plot(model, what = "classification")
```





